openapi: 3.0.3
info:
  title: Todo List ASP.NET Web API
  description: For more information see https://github.com/DanielNieuwoudt/developer-assessment.git
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
security:
  - bearerAuth: []
paths:
  /TodoItems/{id}:
    get:
      tags:
        - TodoItems
      summary: Retrieve a TodoItem by ID
      description: Get the details of a specific TodoItem using its ID.
      operationId: getTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/NotFound"
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    put:
      tags:
        - TodoItems
      summary: Update a TodoItem by ID
      description: Update the details of a specific TodoItem using its ID.
      operationId: putTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/NotFound"
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /TodoItems:
    get:
      tags:
        - TodoItems
      summary: Retrieve all TodoItems
      description: Get a list of all TodoItems.
      operationId: getTodoItems
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItems'
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    post:
      tags:
        - TodoItems
      summary: Create a new TodoItem
      description: Add a new TodoItem to the list.
      operationId: postTodoItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        '401':
          description: Unauthenticated
        '403':
          description: Unauthorized
        '5XX':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BadRequest:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        status:
          type: integer
          description: The HTTP code.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        errors:
          type: object
          description: Collection of validation failures.
          additionalProperties:
            type: array
            items:
              type: string
        traceId:
          type: string
          description: Request identifier for support purposes.  
      additionalProperties: false
      example:
        title: "One or more validation errors occurred."
        type: "https://tools.ietf.org/html/rfc7231#section-6.5.1"
        status: "400"
        detail: "See the errors property for details."
        errors:
          name:
            - "Id"
            - "Id can not be empty"
        traceId: "0HN5D5B7P895B:00000009"
    NotFound:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        status:
          type: integer
          description: The HTTP code.
        traceId:
          type: string
          description: Request identifier for support purposes.
      additionalProperties: false
      example:
        title: "The specified resource was not found."
        type: "https://tools.ietf.org/html/rfc7231#section-6.5.4"
        status: "404"
        traceId: "0HN5D5B7P895B:00000009"          
    InternalServerError:
      type: object
      properties:
        title:
          type: string
          description: Summary of why the request failed.
        type:
          type: string
          description: URI reference that identifies the error type.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        status:
          type: integer
          description: The HTTP code.
        traceId:
          type: string
          description: Request identifier for support purposes.
      additionalProperties: false
      example:
        title: "An error occurred while processing your request."
        type: "https://tools.ietf.org/html/rfc7231#section-6.6.1"
        status: "500"
        traceId: "0HN5D5B7P895B:00000009"          
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        isCompleted:
          type: boolean
      additionalProperties: false
      example:
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        description: "Sample TodoItem"
        isCompleted: false
    TodoItems:
      type: array
      items:
        $ref: '#/components/schemas/TodoItem'