name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Build Docker Compose services
      - name: Build services
        run: docker compose -f docker-compose-tests.yaml build

      # Run Docker Compose services
      - name: Run services
        run: docker compose -f docker-compose.yaml up -d

      # Run tests
      - name: Run tests
        run: docker compose -f docker-compose-tests.yaml run contracts

      # Tear down Docker Compose services
      - name: Tear down services
        if: always()
        run: docker compose -f docker-compose-tests.yaml down